# Generated by Django 6.0.5 on 2026-05-24 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0002_correcao_orientador_projeto_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_enviados', to=settings.AUTH_USER_MODEL)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tcc.entrega')),
            ],
        ),
    ]
